seed = 42
model_type = "mobilenet_v2"
augmentation_type = "default"
output_dir = "models"

[data_args]
trainval_dataset_dir = '/Users/kamil/Developer/Covid19_Classification/data/trainval'
test_dataset_dir = '/Users/kamil/Developer/Covid19_Classification/data/test'
trainval_split_size = 0.9
train_auto_balancing = false
train_augmentation = false
train_batch_size = 64
valtest_batch_size = 64
num_workers = 4

[model_args]
learning_rate = 2e-5

[trainer_args]
deterministic = true

[early_stopping_args]
monitor = 'val_loss'
patience = 5
