seed = 42
model_type = "efficientnet_b5"
augmentation_type = "default"
output_dir = "models"

[data_args]
trainval_dataset_dir = './data/trainval'
trainval_split_size = 0.9
train_auto_balancing = false
train_augmentation = true
train_batch_size = 8
valtest_batch_size = 8
num_workers = 64

[model_args]
learning_rate = 2e-5

[trainer_args]
deterministic = true
#gpus = -1
#accelerator = "ddp"

[early_stopping_args]
monitor = 'val_loss'
patience = 5
