seed = 42
model_type = "mobilenet_v2"
augmentation_type = "default"
output_dir = "models"

[data_args]
trainval_dataset_dir = './data/trainval'
trainval_split_size = 0.9
train_auto_balancing = false
train_augmentation = true
train_batch_size = 64
valtest_batch_size = 64
num_workers = 4

[model_args]
learning_rate = 2e-5

[trainer_args]
deterministic = true
#gpus = 1

[early_stopping_args]
monitor = 'val_loss'
patience = 5
